### ISSUE TITLE
Plate Level thresholds - command line API implications

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#42]
We are sequencing multiplexed barcoded samples on the Illumina MiSeq, initially 96 samples at a time. For some of the planned analyses we will need to process a plate as a batch.

Specifically, some of the information from the main control plate (which included synthetic controls with ITS1 like composition but unique sequences, and single isolates) suggests we should be setting a plate level threshold for excluding contamination (e.g. reads seen less than 100 times should be ignored).

Excluding some early plates, there should always be some samples of just synthetic control sequences, from which we can potentially automatically determine a plate level minimum count for unique reads (e.g. this could be 100 on one plate, but 125 on another plate).

Currently ``thapbi_pict prepare-reads`` and ``thapbi_pict classify-reads`` takes one or more ITS1 FASTQ filenames or folder names. Currently the expectation is that the synthetic controls would be removed by ``thapbi_pict prepare-reads``, so their abundance would have to be recorded or used directly at the end of that command itself.

This suggests ``thapbi_pict prepare-reads`` ought typically to be run on entire plates, and to determine these plate-level settings, we'd typically give a single input directory name (containing the demultiplexed paired FASTQ reads), and the name of the controls (possibly filenames, or file name stems, or a wildcard pattern).

```
$ thapbi_pict prepare-reads -h
...

  --min_count        Integer setting minimum abundance for the unique
                     cleaned reads (e.g. 100), or 'auto' if using --controls.
  --syn_names        Regular expression identifying input filenames which
                     belong to the synthetic controls (e.g. '^CONTROL_').
  --syn_seqs         FASTA file of the expected synthetic control sequences.

```

In the automatic threshold mode, we could for example use the highest abundance of the control reads in the non-control samples (e.g. spill over from a control well on the plate into a real sample).

Would a FASTA file of the expected synthetic control sequences be enough? There will be sequencing and PCR errors, so some level of fuzzy matching is going to be needed to match non-ITS1 reads to the control sequences. Perhaps simple HMMs, which could be combined with the HMM already used with ``hmmscan`` to spot ITS1 sequences?

**Comment by peterjc** [comment]
Current plan after discussion with @widdowquinn is in this situation, first analyse the control samples, and see how many ITS1 sequences are found (should be none), and use that to set the minimum abundance threshold for the non-control samples.

Initially at least, would take the threshold as the maximum unique ITS1 abundance from any control sample.

**Comment by widdowquinn** [comment]
As a note on the reasoning behind the suggestion noted by @peterjc above:

The situation we're controlling for is that a well containing sequences corresponding to a particular, named nursery may contain some reads/sequence from other wells on the plate. It would be unfortunate if reads identified with a particular nursery were identified as a quarantine pathogen, but had originated from some other well. In this case, an "innocent" nursery would be indicted on the grounds of evidence that originated at a different location.

We want to assess the likely quantity/abundance of reads in *any* well that may have come from other wells on the plate. If a threshold can be established where it is almost certain that any reads exceeding the threshold came from the nursery/sample associated with the well, this would give us greater confidence in assigning any particular pathogen to the originating location.

To do this, we should consider the wells containing (ideally) only synthetic controls, and determine the quantitites/abundances of ITS1-matching reads. These can be assumed to have come from other wells on the plate, or otherwise be contamination in the analytical process. Their abundance and distribution can then inform a plate-wide threshold of abundance, where we cannot be confident that reads with lower abundance than the threshold did not arise from "noise" or contamination; we are only confident that reads with abundance above this threshold derive from the well being measured/sequenced.

It would be less appropriate to consider nursery/sample wells of "real" material on the plate, and use the abundance of synthetic controls in these wells to estimate this threshold:

- there are relatively few control wells, with respect to sample/nursery wells. Therefore the total amount of contamination from synthetic -> 'real' wells is expected to have lower detectability
- it is more representative of the 'real' situation to consider ITS1 contamination from any point on the plate/in the process to be possible. By focusing on ITS1 contamination of controls, we are closer to the 'real' contamination potential and abundance of ITS1 cross-contaminating sequences
